# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestSmokeTest():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_adminTest(self):
    self.driver.get("http://127.0.0.1:5500/cse270/teton/1.6/admin.html")
    self.driver.set_window_size(827, 1167)
    self.driver.find_element(By.ID, "username").click()
    elements = self.driver.find_elements(By.ID, "username")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "username").send_keys("dover")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("asdfasdf")
    self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".errorMessage")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".mysubmit:nth-child(4)").click()
  
  def test_directoryTest(self):
    self.driver.get("http://127.0.0.1:5500/cse270/teton/1.6/directory.html")
    self.driver.set_window_size(827, 1168)
    self.driver.find_element(By.ID, "directory-grid").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".gold-member:nth-child(9)").click()
    self.driver.find_element(By.ID, "directory-list").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".gold-member:nth-child(9) > p:nth-child(2)")
    assert len(elements) > 0
  
  def test_homeTest(self):
    self.driver.get("http://127.0.0.1:5500/cse270/teton/1.6/index.html")
    self.driver.set_window_size(1444, 1143)
    self.driver.find_element(By.CSS_SELECTOR, ".header-top").click()
    self.driver.find_element(By.CSS_SELECTOR, ".header-today").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-logo img")
    assert len(elements) > 0
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h1").text == "Teton Idaho"
    assert self.driver.find_element(By.CSS_SELECTOR, ".header-title > h2").text == "Chamber of Commerce"
    assert self.driver.title == "Teton Idaho CoC"
    self.driver.find_element(By.CSS_SELECTOR, ".header-top").click()
    assert self.driver.title == "Teton Idaho CoC"
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".header-title > h2")
    assert len(elements) > 0
  
  def test_joinTest(self):
    self.driver.get("http://127.0.0.1:5500/cse270/teton/1.6/join.html")
    self.driver.set_window_size(909, 1167)
    self.driver.find_element(By.NAME, "fname").click()
    elements = self.driver.find_elements(By.NAME, "fname")
    assert len(elements) > 0
    self.driver.find_element(By.NAME, "fname").send_keys("Andrew")
    self.driver.find_element(By.NAME, "lname").click()
    self.driver.find_element(By.NAME, "lname").send_keys("Halisky")
    self.driver.find_element(By.NAME, "bizname").click()
    self.driver.find_element(By.NAME, "bizname").send_keys("Big Mans")
    self.driver.find_element(By.NAME, "biztitle").click()
    self.driver.find_element(By.NAME, "biztitle").send_keys("Navigator")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.NAME, "email").click()
    elements = self.driver.find_elements(By.NAME, "email")
    assert len(elements) > 0
    self.driver.find_element(By.NAME, "email").send_keys("ajhalisky@gmail.com")
    self.driver.find_element(By.NAME, "cellphone").click()
    self.driver.find_element(By.NAME, "cellphone").send_keys("267-858-2169")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.NAME, "level").click()
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.NAME, "websiteURL").click()
    self.driver.find_element(By.NAME, "websiteURL").send_keys("bigmans.org")
    self.driver.find_element(By.CSS_SELECTOR, "textarea").click()
    self.driver.find_element(By.CSS_SELECTOR, "textarea").send_keys("Big Mans is a nonprofit.")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.NAME, "websiteURL").click()
    self.driver.find_element(By.NAME, "websiteURL").send_keys("www.bigmans.org")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.NAME, "websiteURL").click()
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, "textarea").click()
    self.driver.find_element(By.CSS_SELECTOR, "textarea").click()
    self.driver.find_element(By.NAME, "websiteURL").click()
    self.driver.find_element(By.NAME, "websiteURL").click()
    self.driver.find_element(By.NAME, "websiteURL").click()
    self.driver.find_element(By.NAME, "websiteURL").click()
    self.driver.find_element(By.NAME, "websiteURL").send_keys("https://bigmans.org")
    self.driver.find_element(By.NAME, "submit").click()
  
